ID = 'id'
NAME = 'name'
SYMBOL = 'symbol'
WEBSITE_SLUG = 'website_slug'
RANK = 'rank'
CIRCULATING_SUPPLY = 'circulating_supply'
TOTAL_SUPPLY = 'total_supply'
MAX_SUPPLY = 'max_supply'
LAST_UPDATED = 'last_updated'

PRICE = 'price'
VOLUME_24H = 'volume_24h'
MARKET_CAP = 'market_cap'
PERCENTAGE_CHANGE_1H = 'percentage_change_1h'
PERCENTAGE_CHANGE_24H = 'percentage_change_24h'
PERCENTAGE_CHANGE_7D = 'percentage_change_7d'
PERCENT_CHANGE_1H = 'percent_change_1h'
PERCENT_CHANGE_24H = 'percent_change_24h'
PERCENT_CHANGE_7D = 'percent_change_7d'

TIMESTAMP = 'timestamp'
NUMBER_OF_CRYPTOCURRENCIES = 'num_cryptocurrencies'

VALUE = 'value'
CLASSIFICATION = 'value_classification'
TIME_UNTIL_UPDATE = 'time_until_update'

ERROR = 'error'